steps:
- name: gcr.io/cloud-builders/gcloud
  id: creating-instance-template
  args: ['compute', 'instance-templates', 'create', 'web-inst-temp-$BUILD_ID', '--project=devops-386105', '--machine-type=n1-standard-1', '--metadata=startup-script=sudo apt install git apache2 -y && sudo git clone https://github.com/aju2708/cloud-build.git && sudo cp cloud-build/* /var/www/html/', '--tags=http-server,https-server']
  env:
    - 'CLOUD_BUILD_LOGS_BUCKET=build_logs_lb'
- name: gcr.io/cloud-builders/gcloud
  id: wait-until-stable
  args: ['compute', 'instance-groups', 'managed', 'wait-until', '--stable', 'http-web-group', '--zone=us-central1-a']
- name: gcr.io/cloud-builders/gcloud
  id: updating-mig
  args: ['compute', 'instance-groups', 'managed', 'rolling-action', 'start-update', 'http-web-group', '--version=template=web-inst-temp-$BUILD_ID', '--zone=us-central1-a', '--type=proactive', '--project=devops-386105']
options:
  logging: CLOUD_LOGGING_ONLY
